### ISSUE TITLE
Log field display issues

### ISSUE THREAD

**Issue by Macmueller** [julhac/datagorri#22]
![log-bugged](https://user-images.githubusercontent.com/11724526/37496439-c52955ec-28b2-11e8-9356-6829410cd3ed.jpg)
![log_works](https://user-images.githubusercontent.com/11724526/37496441-c76aa180-28b2-11e8-968a-ebbdaccdc15b.jpg)
These pictures display show how the Log field looks when switching from modeler to scraper. The entry is not correctly displayed (grey field instead of text). The same issue also leads to display issues when scrolling in the scraper.

**Comment by LukasHolzner** [comment]
I have never seen this before. On my Windows ist looks normal...

**Comment by Macmueller** [comment]
Ok, we can test this tomorrow. However if this only appears on OS X this might not be fixable.
