### ISSUE TITLE
Scrolling im Modeler

### ISSUE THREAD

**Issue by LukasHolzner** [julhac/datagorri#3]
Wenn viele Tabellen auf einer Seite oder eine Tabelle aufgeklappt ist, kann nicht mit dem Mausrad gescrollt werden.

**Comment by Macmueller** [comment]
The scrolling feature is integrated but I will leave this issue open, as on OS X are some display errors visible.

**Comment by Macmueller** [comment]
New issue opened for this: 
Log field display issues #22
