### ISSUE TITLE
Missing columns when scraping all columns

### ISSUE THREAD

**Issue by LukasHolzner** [julhac/datagorri#31]
Sometimes columns are missing in the output file when scraping all columns.
Example: When scraping the table from [this page](https://www.transfermarkt.de/fc-bayern-munchen/kader/verein/27/saison_id/1999/plus/1) enumerated all values with letters from a-r, the output does not contain f and p.
This should be investigated and, when possible, fixed.

**Comment by LukasHolzner** [comment]
As far as I can see column p is scraped. And missing column f does not contain any values if you inspect the sites html. It is the first cell of the inner table for image, name and position. The image cell has a rowspan of 2 and only contains an image which is captured in columns g and h. I think that there is nothing to do, but please confirm or say what I should do @julhac

**Comment by julhac** [comment]
@LukasHolzner It should be alright then.
