### ISSUE TITLE
Javascript-Seiten

### ISSUE THREAD

**Issue by LukasHolzner** [julhac/datagorri#8]
Auf einigen Seiten werden die Inhalte auf mehrere Seiten umgebrochen, die dann per Javascript den Inhalt eines \<div\> entsprechend anpassen.
In folgenden Beispiel ist eine solche Tabelle zu sehen: [Elfmetertore von Francesco Totti](https://www.transfermarkt.com/francesco-totti/elfmetertore/spieler/5958/ajax/yw1/saison_id//wettbewerb_id/)
Die URL ändert sich pro Seite mit einem Zusatz wie diesem: /plus/1/page/2

**Comment by LukasHolzner** [comment]
@Macmueller @julhac Muss hier wirklich was unternommen werden?
Mit dem ADD MULTIPLE URLS BY RANGE feature, kann man folgende URL https://www.transfermarkt.com/francesco-totti/elfmetertore/spieler/5958/ajax/yw1/saison_id//wettbewerb_id//page/{X} für alle 6 Seiten hinzufügen. Das einzige was zu beachten ist, ist dass beide Tabellen damit gleichzeitig geblättert werden und für die zweite Tabelle für Werte größer als 2 keine Seiten existieren und somit immer wieder die letzte Seite genommen wird. Bitte um Klärung des Themas!

**Comment by julhac** [comment]
Gibt es eine Möglichkeit zu erkennen, in wie viele Seiten eine Tabelle unterteilt wird? Man könnte dann nur diese scrapen, sodass keine ungewollten Duplikate entstehen.

**Comment by LukasHolzner** [comment]
Das weiß ich nicht. Das könnte evtl gehen wenn man die Pagination der Tabelle zuordnen könnte. Gibt es Situationen in denen Duplikate gewollt sind? Wenn nein, könnte man alle Duplikate entfernen/gar nicht erst hinzufügen, um das Problem zu umgehen...

**Comment by julhac** [comment]
Not needed
