### ISSUE TITLE
Kombination aus wiederholenden und nicht-wiederholenden Tabellen

### ISSUE THREAD

**Issue by LukasHolzner** [julhac/datagorri#9]
Wenn man auf einer Seite sowohl eine nicht-wiederholende als auch eine wiederholende Tabelle hat und scrapen möchte, sollen die Informationen der nicht-wiederholenden Tabelle mit jeder Zeile der wiederholenden Kombiniert werden, dh in jede Zeile der wiederholenden Tabelle im Ergebnis kommt die Information der nicht wiederholenden Tabelle.
Auf folgender [Seite](https://www.transfermarkt.de/fc-bayern-munchen/startseite/verein/27?saison_id=2014) gibt es oben eine nicht-wiederholende Tabelle zur Mannschaft und unten eine wiederholende Tabelle mit den Spielern des aktuellen Kaders der Mannschaft. Wenn man nun beide Tabellen scrapt, soll jeder Spieler des Kaders mit der Information der Mannschaft gespeichert werden.

**Comment by LukasHolzner** [comment]
Mit folgender [Seite](https://www.transfermarkt.de/fc-bayern-munchen/startseite/verein/27?saison_id=2017) und folgender
[Model-Datei](https://github.com/julhac/datagorri/files/1803156/transfermarkt_verein_kader.json.txt) (⚠️ umbenannt, da github .json nicht unterstützt...), wird mit dem geänderten Programm folgendes [Ergebnis](https://github.com/julhac/datagorri/files/1803165/transfermarkt_verein_kader.csv.txt) erzielt.

**Comment by Macmueller** [comment]
Ergebnis sieht sehr gut aus. Wir sollten das aber noch mit anderen Seiten testen, ob es auch zuverlaesslich funktioniert.

**Comment by LukasHolzner** [comment]
Klingt vernünftig, dann lass ich das Issue mal noch offen. Vielleicht kann @julhac da auch ein bisschen helfen, indem er mit der neuen Version rumspielt 😉

**Comment by LukasHolzner** [comment]
Also ich habe den Fehler gefunden: Wenn man keine non-repetitive Tabelle scrapt, ist das dict an der Stelle wo der Key rausgelöscht werden soll leer, was zu dem Fehler führt. Sollte nach dem nächsten push behoben sein!

**Comment by LukasHolzner** [comment]
Should be tested enough. If something comes up you can reopen this issue or create a new one.
